version: "3"
services:
  datagib-postgres:
    container_name: datagib-postgres
    image: postgres:latest
    hostname: datagib-postgres
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'pass'
    ports:
      - 5432:5432
  datagib-frontend:
    container_name: datagib-frontend
    build:
      context: ./frontend/datagib
      dockerfile: Dockerfile
    hostname: datagib-frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/datagib:/frontend/datagib
      - /frontend/datagib/node_modules/
    stdin_open: true
    tty: true
  datagib-backend:
    container_name: datagib-backend
    build:
      context: ./backend/datagib
      dockerfile: Dockerfile
    hostname: datagib-backend
    ports:
      - 8000:8000
    volumes:
      - ./backend/datagib:/backend/datagib
    depends_on:
      - datagib-postgres
    environment:
      WAIT_HOSTS: datagib-postgres:5432
    stdin_open: true
    tty: true
